"""init catalog planner

Revision ID: b962ca0a43e0
Revises: 
Create Date: 2026-09-19 13:18:08.279066
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b962ca0a43e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_year',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='catalog'
    )
    op.create_table('course',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_code', sa.String(length=8), nullable=False),
    sa.Column('course_number', sa.String(length=8), nullable=False),
    sa.Column('course_code', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_code', 'course_number'),
    schema='catalog'
    )
    op.create_index('ix_course_code_trgm', 'course', ['course_code'], unique=False, schema='catalog', postgresql_using='gin', postgresql_ops={'course_code': 'gin_trgm_ops'})
    op.create_table('program',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('school', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='catalog'
    )
    op.create_table('source_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('planner',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planner_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planner_id'),
    schema='planner'
    )
    op.create_table('course_relationship',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_course_id', sa.UUID(), nullable=False),
    sa.Column('to_course_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('group_key', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['from_course_id'], ['catalog.course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_course_id'], ['catalog.course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_course_id', 'to_course_id', 'kind', 'group_key'),
    schema='catalog'
    )
    op.create_table('course_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('credits', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['catalog.academic_year.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['catalog.course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'academic_year_id'),
    schema='catalog'
    )
    op.create_table('ingestion_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['catalog.source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('parse_review_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['catalog.course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('program_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['catalog.academic_year.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['catalog.program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'academic_year_id'),
    schema='catalog'
    )
    op.create_table('term',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['catalog.academic_year.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='catalog'
    )
    op.create_table('student_program',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planner_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('program_role', sa.String(length=32), nullable=False),
    sa.Column('intake_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planner_id'], ['planner.planner.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['catalog.program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='planner'
    )
    op.create_table('combination_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_version_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('expression_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['program_version_id'], ['catalog.program_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('course_offering',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('course_version_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['catalog.course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_version_id'], ['catalog.course_version.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['catalog.term.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'term_id'),
    schema='catalog'
    )
    op.create_table('course_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('course_version_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('expression_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['catalog.course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_version_id'], ['catalog.course_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('requirement_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_version_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('min_credits', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['catalog.requirement_group.id'], ),
    sa.ForeignKeyConstraint(['program_version_id'], ['catalog.program_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('staging_course',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('subject_code', sa.String(length=8), nullable=True),
    sa.Column('course_number', sa.String(length=8), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['catalog.ingestion_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('student_course',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planner_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['catalog.course.id'], ),
    sa.ForeignKeyConstraint(['planner_id'], ['planner.planner.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['catalog.term.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planner_id', 'course_id', 'term_id'),
    schema='planner'
    )
    op.create_table('class_section',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('section_code', sa.String(length=16), nullable=False),
    sa.Column('class_nbr', sa.String(length=16), nullable=True),
    sa.Column('instructor', sa.String(length=255), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=True),
    sa.Column('enrol', sa.Integer(), nullable=True),
    sa.Column('avail', sa.Integer(), nullable=True),
    sa.Column('wait', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['catalog.course_offering.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'section_code'),
    schema='catalog'
    )
    op.create_table('requirement_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['catalog.course.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['catalog.requirement_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('meeting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.String(length=8), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('venue', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['catalog.class_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_table('requirement_credit_allocation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planner_id', sa.UUID(), nullable=False),
    sa.Column('requirement_item_id', sa.UUID(), nullable=False),
    sa.Column('student_course_id', sa.UUID(), nullable=False),
    sa.Column('credits', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['planner_id'], ['planner.planner.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_item_id'], ['catalog.requirement_item.id'], ),
    sa.ForeignKeyConstraint(['student_course_id'], ['planner.student_course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='planner'
    )
    op.create_table('student_class_selection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planner_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['planner_id'], ['planner.planner.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['catalog.class_section.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planner_id', 'section_id'),
    schema='planner'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_class_selection', schema='planner')
    op.drop_table('requirement_credit_allocation', schema='planner')
    op.drop_table('meeting', schema='catalog')
    op.drop_table('requirement_item', schema='catalog')
    op.drop_table('class_section', schema='catalog')
    op.drop_table('student_course', schema='planner')
    op.drop_table('staging_course', schema='catalog')
    op.drop_table('requirement_group', schema='catalog')
    op.drop_table('course_rule', schema='catalog')
    op.drop_table('course_offering', schema='catalog')
    op.drop_table('combination_rule', schema='catalog')
    op.drop_table('student_program', schema='planner')
    op.drop_table('term', schema='catalog')
    op.drop_table('program_version', schema='catalog')
    op.drop_table('parse_review_queue', schema='catalog')
    op.drop_table('ingestion_run', schema='catalog')
    op.drop_table('course_version', schema='catalog')
    op.drop_table('course_relationship', schema='catalog')
    op.drop_table('planner', schema='planner')
    op.drop_table('source_document', schema='catalog')
    op.drop_table('program', schema='catalog')
    op.drop_index('ix_course_code_trgm', table_name='course', schema='catalog', postgresql_using='gin', postgresql_ops={'course_code': 'gin_trgm_ops'})
    op.drop_table('course', schema='catalog')
    op.drop_table('academic_year', schema='catalog')
    # ### end Alembic commands ###
